# Generated by Django 3.2.8 on 2021-11-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211114_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_city',
            field=models.CharField(blank=True, max_length=150, verbose_name='текущий город'),
        ),
        migrations.AddField(
            model_name='user',
            name='hometown',
            field=models.CharField(blank=True, max_length=150, verbose_name='родной город'),
        ),
    ]
